apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: The web server's http port.
      labels:
        application: staging-keycloak
      name: staging-keycloak
    spec:
      ports:
        - port: 8080
          targetPort: 8080
      selector:
        deploymentConfig: staging-keycloak
  - apiVersion: route.openshift.io/v1
    id: staging-keycloak
    kind: Route
    metadata:
      annotations:
        description: Route for application's service.
      labels:
        application: staging-keycloak
        public: 'true'
      name: staging-keycloak
    spec:
      host: idp-mock-okr.ocp.cloudscale.puzzle.ch
      tls:
        termination: edge
      to:
        name: staging-keycloak
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: staging-keycloak
      name: staging-keycloak
    spec:
      replicas: 1
      selector:
        deploymentConfig: staging-keycloak
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: staging-keycloak
            deploymentConfig: staging-keycloak
          name: staging-keycloak
        spec:
          containers:
            - args:
                - start-dev
              env:
                - name: KEYCLOAK_ADMIN
                  value: admin
                - name: KEYCLOAK_ADMIN_PASSWORD
                  value: admin
                - name: KC_PROXY
                  value: edge
              image: quay.io/keycloak/keycloak:21.1.1
              livenessProbe:
                failureThreshold: 100
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
              name: staging-keycloak
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 300
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
              securityContext:
                privileged: false
              volumeMounts:
                - mountPath: /opt/keycloak/data
                  name: empty
          volumes:
            - emptyDir: {}
              name: empty
      triggers:
        - type: ConfigChange
kind: List
metadata: {}
