---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-okr-application
  labels:
    app: staging-okr-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-okr-application
  template:
    metadata:
      labels:
        app: staging-okr-application
    spec:
      containers:
        - name: staging-okr-application
          image: registry.puzzle.ch/puzzle/okr:2.0.32-STAGING
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: debug
            - name: SPRING_LDAP_URLS
              valueFrom:
                secretKeyRef:
                  key: url
                  name: ldap-credentials
            - name: SPRING_LDAP_BASE
              valueFrom:
                secretKeyRef:
                  key: base
                  name: ldap-credentials
            - name: SPRING_LDAP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: ldap-credentials
            - name: SPRING_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ldap-credentials
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: database-credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: database-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: https://sso.puzzle.ch/auth/realms/pitc
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: https://sso.puzzle.ch/auth/realms/pitc/protocol/openid-connect/certs
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-ID
              value: pitc_okr_prod
            - name: OKR_USER_CHAMPION_USERNAMES
              valueFrom:
                secretKeyRef:
                  key: usernames
                  name: okr-champions
          ports:
            - name: http
              containerPort: 8080
