---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-okr-application
  labels:
    app: staging-okr-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-okr-application
  template:
    metadata:
      labels:
        app: staging-okr-application
    spec:
      containers:
        - name: staging-okr-application
          image: registry.puzzle.ch/puzzle/okr:1.0.38-STAGING
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: database-credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: database-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
          ports:
            - name: http
              containerPort: 8080
