---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-okr-application
  labels:
    app: staging-okr-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-okr-application
  template:
    metadata:
      labels:
        app: staging-okr-application
    spec:
      containers:
        - name: staging-okr-application
          image: registry.puzzle.ch/puzzle/okr:1.0.18-STAGING
          env:
            - name: SPRING_ACTIVE_PROFILES
              value: dev
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: database-credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: database-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://staging-okr-oidc-mock:8000
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-provider-mock
  labels:
    app: oidc-provider-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-provider-mock
  template:
    metadata:
      labels:
        app: oidc-provider-mock
    spec:
      volumes:
        - name: config
          configMap:
            name: config
      containers:
        - name: oidc-provider-mock
          image: registry.puzzle.ch/puzzle/oidc-provider-mock:d4ae14c1
          volumeMounts:
            - name: config
              mountPath: "/tmp/"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: CONFIG_FILE_PATH
              value: /tmp/config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: staging-okr-oidc-mock
spec:
  selector:
    app: oidc-provider-mock
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
