---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-okr-application
  labels:
    app: staging-okr-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-okr-application
  template:
    metadata:
      labels:
        app: staging-okr-application
    spec:
      containers:
        - name: staging-okr-application
          image: registry.puzzle.ch/puzzle/okr:1.0.70-STAGING
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: https://idp-mock-okr.ocp-internal.cloudscale.puzzle.ch/jwks
            - name: SPRING_PROFILES_ACTIVE
              value: staging
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: debug
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: database-credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: database-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: https://idp-mock-okr.ocp-internal.cloudscale.puzzle.ch/
            - name: OAUTH_SCOPE
              value: profile openid pitc preferred_username given_name family_name email
          ports:
            - name: http
              containerPort: 8080
