---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-okr-application
  labels:
    app: staging-okr-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-okr-application
  template:
    metadata:
      labels:
        app: staging-okr-application
    spec:
      containers:
        - name: staging-okr-application
          image: registry.puzzle.ch/puzzle/okr:1.0.98-STAGING
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: debug
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: database-credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: database-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-credentials
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: https://idp-mock-okr.ocp-internal.cloudscale.puzzle.ch/realms/pitc
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: https://idp-mock-okr.ocp-internal.cloudscale.puzzle.ch/realms/pitc/protocol/openid-connect/certs
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-ID
              value: pitc_okr_staging
          ports:
            - name: http
              containerPort: 8080
