---
apiVersion: v1
kind: Service
metadata:
  name: oidc-provider-mock
spec:
  selector:
    app: oidc-provider-mock
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http