apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: okr-application-image-stream
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: registry.puzzle.ch/yminder/puzzle-okr:latest
    referencePolicy:
      type: Source
