---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okr-application
  labels:
    app: okr-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okr-application
  template:
    metadata:
      labels:
        app: okr-application
    spec:
      containers:
        - name: okr-application
          image: okr-application-image-stream:latest
          env:
            - name: SPRING_ACTIVE_PROFILES
              value: prod
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: db-credentials
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: db-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-credentials
          ports:
              - name: http
                containerPort: 8080

